### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by OBKoro1** [OBKoro1/stop-mess-around#1]
![image](https://user-images.githubusercontent.com/24698201/123365177-5d366500-d5a8-11eb-95c3-54bc4e2997ab.png)

**Comment by pan463859** [comment]
可以尝试和pinbox一样添加组合快捷键~

**Comment by OBKoro1** [comment]
> 可以尝试和pinbox一样添加组合快捷键~

可以具体说说吗，需要快捷键来做什么？

**Comment by pan463859** [comment]
> > 可以尝试和pinbox一样添加组合快捷键~
> 
> 可以具体说说吗，需要快捷键来做什么？

比如说ctrl+l弹出配置列表
ctrl+xxx添加当前网页进屏蔽列表之类的

**Comment by OBKoro1** [comment]
可以的 这个需求记下了，下次迭代就做一下 😊

**Comment by FrizzleFur** [comment]
@OBKoro1 第二点我是想说如果需要屏蔽网站较多的时候，可以支持一键/批量配置，支持快捷搜索，当然，前提是很多人用就会有类似的需求，想法仅供参考

**Comment by OBKoro1** [comment]
> @OBKoro1 第二点我是想说如果需要屏蔽网站较多的时候，可以支持一键/批量配置，支持快捷搜索，当然，前提是很多人用就会有类似的需求，想法仅供参考

谢谢你的建议、

1. 批量配置可以从摸鱼列表上批量添加。
2. 表格的搜索功能已经有了。

**Comment by OBKoro1** [comment]
@pan463859 

无论是弹出管理面板 ，还是添加摸鱼网站，都应该是一个低频的操作，而且如果这样做的话很容易在网站中引发其他事件，所以插件不准备监听网站中的快捷键。

对于添加摸鱼网站，插件在popup中提供了一个新功能：添加当前激活网页到摸鱼网站列表中。

点击后，自动打开管理面板页面的新增摸鱼网站的弹窗并且填入摸鱼网址。

下面是一个gif演示: 

![](https://github.com/OBKoro1/stop-mess-around/blob/master/static/popupAdd.gif?raw=true)

**Comment by pan463859** [comment]
> @pan463859
> 
> 无论是弹出管理面板 ，还是添加摸鱼网站，都应该是一个低频的操作，而且如果这样做的话很容易在网站中引发其他事件，所以插件不准备监听网站中的快捷键。
> 
> 对于添加摸鱼网站，插件在popup中提供了一个新功能：添加当前激活网页到摸鱼网站列表中。
> 
> 点击后，自动打开管理面板页面的新增摸鱼网站的弹窗并且填入摸鱼网址。
> 
> 下面是一个gif演示:
> 
> ![](https://github.com/OBKoro1/stop-mess-around/blob/master/static/popupAdd.gif?raw=true)

**点赞~**
