### ISSUE TITLE
额外的icon资源请求

### ISSUE THREAD

**Issue by haoruilee** [OBKoro1/stop-mess-around#10]
#### 描述bug

本插件在任何网页上均会请求[GitHub Star数](https://img.shields.io/github/stars/OBKoro1/stop-mess-around?style=social)，额外的资源请求会造成浏览的不便，且这个资源本身对使用者没有意义

#### 复现方式(必填)

1. 在任何情况下刷新网页，打开调试模式，都可以看到名为stop-mess-around?style=social的资源正在加载

#### 预期行为

这个icon本身对于插件使用者没有意义，不应该被请求

**Comment by OBKoro1** [comment]
hi 你好 请更新插件，这个问题已解决

如果觉得插件还不错的话，就点个Star吧~ 😄
