### ISSUE TITLE
摸鱼网址问题

### ISSUE THREAD

**Issue by TerryZhang-EE** [OBKoro1/stop-mess-around#12]
淘宝网址不识别
淘宝网选项默认网址是:(http://www.taobao.com/)
淘宝网地址是(https://www.taobao.com/)
我,目前在设置里更改后可以识别了,希望作者能在默认设置里修正一下

**Comment by OBKoro1** [comment]
更新插件，现在用域名进行判断，可以更新一下默认摸鱼网址~
如果觉得插件不错，就点个Star吧~ ❤️
