### ISSUE TITLE
建议把日拱一卒的位置放中间，或者更方便点击的位置，以及弹窗界面计时关闭

### ISSUE THREAD

**Issue by Dustin-Hayes-Hong** [OBKoro1/stop-mess-around#14]
### 想法与建议
我原本以为计时关闭的功能，是自动关闭窗口，等了很久才发现需要点击“日拱一卒”才会关闭。
只能说自己没有文化，没直接明白“日拱一卒”这个键的功能。
如果整个弹窗界面也能设计倒计时，或许会更合理。
比如说倒计时10秒，在这10秒内没有点击休息一下，就会关闭窗口。
在人猝不及防的时候，摸鱼就结束了。
然后就是，“日拱一卒”可以更大更显眼，位置居中。然后“休息一下”位置放在角落，更小（如果能随机位置就更好了，配合自动关闭窗口，绝杀）

**Comment by OBKoro1** [comment]
倒计时功能已集成，关闭页面和其他按钮的大小，现在有差异，显得关闭页面按钮更突出。
如果觉得插件不错，就点个Star吧 ❤️~
![image](https://user-images.githubusercontent.com/24698201/201608779-11166501-8592-44fc-9e91-86bb7fb10f3b.png)
