### ISSUE TITLE
web_accessible_resources清单键

### ISSUE THREAD

**Issue by con-yu** [OBKoro1/stop-mess-around#15]
开启拓展后控制台会报如下一条错误：
Denying load of chrome-extension://gbjbkekbbjbieijpebieifkmahlagncm/fonts/element-icons.ttf. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.

请问这是什么地方出错了吗？

**Comment by OBKoro1** [comment]
更新插件 这个问题，解决好了~ 
如果觉得插件还不错，就点个Star吧~❤️

**Comment by OBKoro1** [comment]
插件新版本已经发布了，谷歌商店正在审核，等审核好了，我通知一下~

**Comment by OBKoro1** [comment]
插件已发布~如果觉得插件还不错，就点个Star吧~❤️
