### ISSUE TITLE
Firefox无法使用

### ISSUE THREAD

**Issue by Force1ess** [OBKoro1/stop-mess-around#16]
#### 描述bug(必填)

Firefox中使用该拓展并打开网址并不会有效果，chrome会有

提供复现步骤和截图。

![图片](https://user-images.githubusercontent.com/72636351/184792470-f0a161b7-5870-4e10-b54c-69c6609ee611.png)
![图片](https://user-images.githubusercontent.com/72636351/184792481-baf384e9-d4f9-406f-bda9-0e1c310561cb.png)
![图片](https://user-images.githubusercontent.com/72636351/184792520-ed7cec2e-3e85-47e3-8049-ea869611fef5.png)

**Comment by MapleWithered** [comment]
+1

**Comment by baozidai** [comment]
我也出现了这个情况

**Comment by FrankJingHao** [comment]
哥，firefox的插件商店2.0.8版本该更新为2.1.2了

**Comment by Force1ess** [comment]
> 哥，firefox的插件商店2.0.8版本该更新为2.1.2了

真的吗，那我关了

**Comment by GrootLiu** [comment]
> 哥，firefox的插件商店2.0.8版本该更新为2.1.2了

好像还是 2.0.8 呢
