### ISSUE TITLE
[Bug] 无法自定义添加励志语录

### ISSUE THREAD

**Issue by CaseMisty** [OBKoro1/stop-mess-around#19]
#### 描述bug(必填)

添加励志语录弹窗中点击"保存添加"按钮均不好使

#### 复现方式(必填)
1. 我在"随机励志语录"tab中, 点击了"清空所有随机励志语录"  (不知道与次操作有没有关)
2. 在"添加"tab, 输入后,点击添加时, 发现语录,标题,按钮 都无法添加, 控制台报错

<img width="605" alt="image" src="https://user-images.githubusercontent.com/12370210/202823306-054b745d-5094-481b-af9e-5a7292faf685.png">
<img width="529" alt="image" src="https://user-images.githubusercontent.com/12370210/202823361-d2a50d45-0607-48ba-abf5-b5342404ea63.png">

**Comment by OBKoro1** [comment]
@CaseMisty  更新插件，该问题已修复~
觉得插件不错的话，就点个Star吧~ ❤️
