### ISSUE TITLE
新功能建议：摸鱼时间段设置

### ISSUE THREAD

**Issue by SeptemberHX** [OBKoro1/stop-mess-around#3]
**当前的效果/功能**：

只能手动去关掉摸鱼检测

**你期待的效果/功能**：

允许用户设定时间段，在时间段内自动停止/启用摸鱼检测

**描述你考虑过的备选方案**

无

**其他相关**

无

**Comment by OBKoro1** [comment]
现在在网站上匹配到摸鱼网站，有一个休息一下的功能，这个功能会更加方便，定时的功能每次需要设置，而且每天的情况和时间段不一样，如果想休息，直接点休息一下会更好。
更新一下插件，即可使用。
如果觉得插件还不错的话，就点个Star吧~ 
好用的话，可以推荐给朋友哈😊
![image](https://user-images.githubusercontent.com/24698201/139775154-557bf22b-55fd-409d-ad56-216ccaf4d720.png)
