### ISSUE TITLE
时间统计异常，同时点击休息后反复弹出

### ISSUE THREAD

**Issue by Hou-Xiaoxuan** [OBKoro1/stop-mess-around#5]
bug1：时间经常统计异常，表现为每天刚开始市场为负数或几百分钟。
同时此时跟容易出现bug2
bug2: 点击休息后仍然反复弹出
![bug2](https://www.hualigs.cn/image/6207a28966874.jpg)

环境为 
manjaro
microsoft-edge-deb-bin 100.0.1156.1.1

**Comment by OBKoro1** [comment]
你是用EDGE使用的是吗？ 我没试过EDGE，你可以试下用chrome浏览器，看会不会出现问题。

**Comment by OBKoro1** [comment]
hi 你好 这个问题已经修复了，并且可以在[Edge扩展商店](https://microsoftedge.microsoft.com/addons/detail/stopmessaroundfile/mdiafefnlaaefmfgjbeejpppkdhghmaj)中下载

觉得插件还不错的话，就点个Star吧~
