### ISSUE TITLE
Firefox 插件跳转链接错误

### ISSUE THREAD

**Issue by Nuofan-SUSTech** [OBKoro1/stop-mess-around#7]
从 Firefox 插件商店下载安装的此插件：
![image](https://user-images.githubusercontent.com/80809557/161189647-86c1cb16-89dd-4a6a-9235-ccd703a7149b.png)

使用的时候进入管理面板提示找不到地址，地址栏上写的应该是 Chrome 的跳转链接：
![跳转链接错误](https://user-images.githubusercontent.com/80809557/161190452-54979b2f-5bc2-41a7-823b-2595787197d1.gif)

推测是把 Chrome 版本的插件上传到了 Firefox 的插件商店上去了？

**Comment by OBKoro1** [comment]
hi 你好 插件已兼容firefox, 可前往[应用市场](https://addons.mozilla.org/zh-CN/firefox/addon/stop-mess-around1/)下载使用插件。

如果觉得插件还不错的话，就点个Star吧~
