### ISSUE TITLE
建议禁用按下 esc 关闭弹框

### ISSUE THREAD

**Issue by xiaorong61** [OBKoro1/stop-mess-around#8]
**你期待的效果/功能**：

当访问不希望的网页时，弹框可以 esc 取消，这不大好。
希望按下 esc 不取消弹框。

**描述你考虑过的备选方案**

希望按下 esc 不取消弹框。

**Comment by OBKoro1** [comment]
hi 你好 请更新插件，这个问题已解决

如果觉得插件还不错的话，就点个Star吧~ 😄

**Comment by xiaorong61** [comment]
有效果，已 star。:smile:
