### ISSUE TITLE
部分屏幕分辨率下励志语录对话框编辑和删除按钮上下排布不美观

### ISSUE THREAD

**Issue by 25252www** [OBKoro1/stop-mess-around#9]
chrome-extension://gbjbkekbbjbieijpebieifkmahlagncm/options.html 页面点击励志语录弹出的dialog中右侧两个button上下排布，不太美观，屏幕尺寸1920x937，如果方便可以再做下自适应~
![image](https://user-images.githubusercontent.com/45707511/167876272-01603f53-3731-4f77-a673-78bc5acd8aa7.png)

**Comment by OBKoro1** [comment]
hi 你好 请更新插件，这个问题已解决

如果觉得插件还不错的话，就点个Star吧~ 😄
